#probability of occupation of one grid


#max probability
p_max:  99
#min probability
p_min:  1
#probability when unknown
p_unknown:  50
#probability when test a grid once
p_fill: 90
#probability when test not grid 
p_clear: 20




#sensor parameter
range_max: [12.0,12.0, 12.0, 12.0, 12.0, 12.0]
range_min: [1.0,1.0, 1.0, 1.0, 1.0, 1.0]
laser_x: [+3.6,-1.0,+3.3,+3.3,-0.5,-0.5]
laser_y: [+0.0,+0.0,-0.8,+0.8,-0.8,+0.8]
laser_yaw: [-45,-225,-125,35,-145,55]
radiation_num_divider: [4,4,4,4,4,4]


#visualization
#binary0 or scalar 1
visual_way: 0
binary_threshold: 50